---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tawfiqulbari.work # change to your domain
  namespace: traefik # add to traefik namespace so it can use it (you DO NOT need it in each app namespace!!!)
spec:
  secretName: tawfiqulbari-tls # change to your secretname
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.tawfiqulbari.work" # change to your domain
  dnsNames:
  - "*.tawfiqulbari.work" # change to your domain
  - tawfiqulbari.work # change to your domain
